<?xml version="1.0" encoding="UTF-8"?>
<!--
DTD
-->
<!DOCTYPE alumnos [
    <!ELEMENT alumnos (alumno+)>
    <!ELEMENT alumno (nombre,apellido,curso,(nota_media|nota_final))>
    <!ATTLIST alumno num_exp CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT curso (#PCDATA)>
    <!ELEMENT nota_media (#PCDATA)>
    <!ELEMENT nota_final (#PCDATA)>
]>
<alumnos>
    <alumno num_exp="A001" >
        <nombre>Constantino</nombre>
        <apellido>Lantigua Calderín</apellido>
        <curso>2º ESO</curso>
        <nota_media>7</nota_media>
    </alumno>
    <alumno num_exp="A002" >
        <nombre>Jose</nombre>
        <apellido>Cruz Caballero</apellido>
        <curso>2º ESO</curso>
        <nota_final>9</nota_final>
    </alumno>
</alumnos>